<?php

return [
    'name' => 'Wpbox',
    'google_maps_api_key' => env('GOOGLE_MAPS_API_KEY', ''),
    'google_maps_enabled' => env('GOOGLE_MAPS_ENABLED_ON_DETAILS', true),
    'api_docs' => env('WPBOX_API_DOCS', 'https://documenter.getpostman.com/view/8538142/2s9Ykn8gvj'),
    'pp_url' => env('PRIVACY_POLICY_URL', '#'),
    'terms_url' => env('TERMS_OF_SERVICE_URL', '#'),
    'disclaimer_url' => env('DISCLAIMER_URL', '#'),
    'tw' => env('X_URL', '#'),
    'fb' => env('FACEBOOK_URL', '#'),
    'insta' => env('INSTAGRAM_URL', '#'),
    'one_signal_app_id' => env('ONE_SIGNAL_APP_ID', ''),
    'openai_api_key' => env('OPENAI_API_KEY', ''),
    'openai_api_key_demo' => env('OPENAI_API_KEY_DEMO', ''),
    'openai_max_tokens' => env('OPENAI_MAX_TOKENS', 256),
    'openai_enabled' => env('OPENAI_ENABLED', true),
    'openai_model' => env('OPENAI_MODEL', 'gpt-3.5-turbo'),
    'available_languages' => env('AVAILABLE_LANGUAGES', 'English,Spanish,German,Italian,Portuguese,Dutch,French,Japanese,Chinese'),
    'campaign_sending_batch' => env('CAMPAIGN_SENDING_BATCH', 500),
    'campaign_sending_type' => env('CAMPAIGN_SENDING_TYPE', 'normal'),
    'campaign_async_dispatch' => env('CAMPAIGN_ASYNC_DISPATCH', true),
    'campaign_max_recipients' => env('CAMPAIGN_MAX_RECIPIENTS', 1000000),
    'campaign_preparation_chunk' => env('CAMPAIGN_PREPARATION_CHUNK', 2000),
    'campaign_insert_chunk' => env('CAMPAIGN_INSERT_CHUNK', 1000),
    'campaign_audience_preview_limit' => env('CAMPAIGN_AUDIENCE_PREVIEW_LIMIT', 500),
    'campaign_preparation_queue' => env('CAMPAIGN_PREPARATION_QUEUE', 'campaigns'),
    'campaign_dispatch_queue' => env('CAMPAIGN_DISPATCH_QUEUE', 'campaigns'),
    'campaign_send_queue' => env('CAMPAIGN_SEND_QUEUE', 'campaigns'),
    'whatsapp_messages_per_second' => env('WHATSAPP_MESSAGES_PER_SECOND', 80),
    'hostpinnacle_bulk_max_batch' => env('HOSTPINNACLE_BULK_MAX_BATCH', 10000),
    'campaign_dispatch_token' => env('CAMPAIGN_DISPATCH_TOKEN', ''),
    'mobile_app_ios_url' => env('MOBILE_APP_IOS_URL', '#'),
    'mobile_app_android_url' => env('MOBILE_APP_ANDROID_URL', '#'),
    'mobile_app_install_token' => env('MOBILE_APP_INSTALL_TOKEN', ''),
    'mobile_app_version' => env('MOBILE_APP_VERSION', '4.2.0'),
    'chat_page_size' => env('CHAT_PAGE_SIZE', 6),
];
