<?php

namespace Modules\WhatsappcallWorker\Console;

use Illuminate\Console\Command;
use Symfony\Component\Process\Process;

class StartWorkerCommand extends Command
{
    protected $signature = 'whatsappcall:worker
                            {--install : Run npm install in the worker directory first}
                            {--port= : Worker HTTP port (default from config)}';

    protected $description = 'Start the built-in WhatsApp AI voice worker (Node.js)';

    public function handle(): int
    {
        $workerPath = config('whatsappcallworker.worker_path');

        if (! is_dir($workerPath)) {
            $this->error('Worker directory not found: '.$workerPath);

            return self::FAILURE;
        }

        if (! $this->commandExists('node')) {
            $this->error('Node.js is not installed. Install Node 18+ and try again.');

            return self::FAILURE;
        }

        if ($this->option('install') || ! is_dir($workerPath.'/node_modules')) {
            $this->info('Installing worker dependencies (npm install)...');
            $install = new Process(['npm', 'install'], $workerPath, null, null, 600);
            $install->run(function ($type, $buffer) {
                $this->output->write($buffer);
            });
            if (! $install->isSuccessful()) {
                $this->error('npm install failed.');

                return self::FAILURE;
            }
        }

        $port = $this->option('port') ?: config('whatsappcallworker.port', 8787);
        $host = config('whatsappcallworker.host', '127.0.0.1');
        $callbackUrl = rtrim(config('whatsappcall.laravel_callback_url', 'http://127.0.0.1:8000'), '/');
        $secret = config('whatsappcall.ai_worker_secret', '');

        $openAiKey = config('wpbox.openai_api_key', env('OPENAI_API_KEY', ''));
        $workerMode = env('WHATSAPP_AI_WORKER_MODE', $openAiKey ? 'realtime' : 'stub');

        $this->syncWorkerEnvFile($workerPath, [
            'PORT' => (string) $port,
            'HOST' => $host,
            'LARAVEL_APP_URL' => $callbackUrl,
            'WHATSAPP_AI_LARAVEL_CALLBACK_URL' => $callbackUrl,
            'WHATSAPP_AI_WORKER_SECRET' => $secret,
            'WORKER_MODE' => $workerMode,
            'WHATSAPP_AI_WORKER_MODE' => $workerMode,
            'OPENAI_API_KEY' => $openAiKey,
            'OPENAI_REALTIME_MODEL' => env('OPENAI_REALTIME_MODEL', 'gpt-realtime'),
            'OPENAI_REALTIME_VOICE' => env('OPENAI_REALTIME_VOICE', 'alloy'),
            'WORKER_DEBUG' => '1',
        ]);

        $env = array_merge($_ENV, [
            'PORT' => (string) $port,
            'HOST' => $host,
            'LARAVEL_APP_URL' => $callbackUrl,
            'WHATSAPP_AI_LARAVEL_CALLBACK_URL' => $callbackUrl,
            'WHATSAPP_AI_WORKER_SECRET' => $secret,
            'WORKER_MODE' => $workerMode,
            'WHATSAPP_AI_WORKER_MODE' => $workerMode,
            'OPENAI_API_KEY' => $openAiKey,
            'OPENAI_REALTIME_MODEL' => env('OPENAI_REALTIME_MODEL', 'gpt-realtime'),
            'OPENAI_REALTIME_VOICE' => env('OPENAI_REALTIME_VOICE', 'alloy'),
        ]);

        $this->info("Starting WhatsApp AI worker on http://{$host}:{$port} (mode={$workerMode})");
        $this->line('OpenAI API key: '.($openAiKey ? substr($openAiKey, 0, 7).'...'.substr($openAiKey, -4).' ('.strlen($openAiKey).' chars)' : 'NOT SET — spoken AI will not work'));
        if ($workerMode === 'realtime' && ! $openAiKey) {
            $this->warn('WORKER_MODE=realtime but OPENAI_API_KEY is empty. Calls will fall back to STUB (silent).');
            $this->line('Set OPENAI_API_KEY in Laravel .env (config wpbox.openai_api_key) and restart this command.');
        }
        $this->line('Worker → Laravel callbacks: '.$callbackUrl.'/api/whatsappcall/worker');
        $this->line('WhatsApp Calling setup → AI worker URL: http://'.$host.':'.$port);
        if (str_contains(config('app.url', ''), 'ngrok')) {
            $this->warn('APP_URL is ngrok — keep that for webhooks. Worker uses WHATSAPP_AI_LARAVEL_CALLBACK_URL for local callbacks.');
        }
        $this->line('Press Ctrl+C to stop.');

        $process = new Process(['npm', 'start'], $workerPath, $env);
        $process->setTimeout(null);
        $process->run(function ($type, $buffer) {
            $this->output->write($buffer);
        });

        return $process->isSuccessful() ? self::SUCCESS : self::FAILURE;
    }

    /**
     * @param  array<string, string>  $vars
     */
    private function syncWorkerEnvFile(string $workerPath, array $vars): void
    {
        $lines = [
            '# Auto-generated by php artisan whatsappcall:worker',
            '# Restart the worker after changing Laravel .env',
        ];

        foreach ($vars as $key => $value) {
            $escaped = str_replace(["\r", "\n"], '', (string) $value);
            if (preg_match('/[\s#="\'\\\\]/', $escaped)) {
                $escaped = '"'.str_replace('"', '\\"', $escaped).'"';
            }
            $lines[] = "{$key}={$escaped}";
        }

        file_put_contents($workerPath.'/.env', implode("\n", $lines)."\n");
        $this->line('Synced worker/.env from Laravel config');
    }

    private function commandExists(string $command): bool
    {
        $process = new Process(['which', $command]);
        $process->run();

        return $process->isSuccessful();
    }
}
